package config

import (
	"time"
)

//config keys
const (
	//EnableConnectionPool bool ...
	EnableConnectionPool = "EnableConncetionPool"
	//MaxConnectionsPerHost int ...
	MaxConnectionsPerHost = "MaxConnectionsPerHost"
	//MaxTotalConnections int ...
	MaxTotalConnections = "MaxTotalConnections"
	//ConnectTimeout time.Duration ...
	ConnectTimeout = "ConnectTimeout"
	//ReadWriteTimeout time.Duration ...
	ReadWriteTimeout = "ReadWriteTimeout"
	//RequestTimeout time.Duration ...
	RequestTimeout = "RequestTimeout"
	//MaxAutoRetries int ...
	MaxAutoRetries = "MaxAutoRetries"
	//MaxAutoRetriesNextServer int ...
	MaxAutoRetriesNextServer = "MaxAutoRetriesNextServer"
	//OKToRetryOnAllOperations bool ...
	OKToRetryOnAllOperations = "OKToRetryOnAllOperations"
	//Port int ...
	Port = "Port"
	//ListOfServers string ...
	ListOfServers = "ListOfServers"
	//ConnectionFailureThreshold int ...
	ConnectionFailureThreshold = "ConnectionFailureThreshold"
	//CircuitTrippedTimeoutFactor int ...
	CircuitTrippedTimeoutFactor = "CircuitTrippedTimeoutFactor"
	//CircuitTripMaxTimeout time.Duration ...
	CircuitTripMaxTimeout = "CircuitTripMaxTimeout"
	//ResponseTimeWindowSize int
	ResponseTimeWindowSize = "ResponseTimeWindowSize"
	//RequestCountsSlidingWindowSize
	RequestCountsSlidingWindowSize = "RequestCountsSlidingWindowSize"
	//PingInterval time.Duration ...
	PingInterval = "PingInterval"
	//PingStrategy string ...
	PingStrategy = "PingStrategy"
	//LoadBalancerRule string ...
	LoadBalancerRule = "LoadBalancerRule"
	//LoadBalancerKey string ...
	LoadBalancerKey = "LoadBalancerKey"
	//ListOfServersPollingInterval time.Duration ...
	ListOfServersPollingInterval = "ListOfServersPollingInterval"
	//ConcurrencyRateLimitSwitch bool
	ConcurrencyRateLimitSwitch = "ConcurrencyRateLimitSwitch"
	//TokenBucketRateLimitSwitch boll ...
	TokenBucketRateLimitSwitch = "TokenBucketRateLimitSwitch"
	//TokenBucketCapacity int ...
	TokenBucketCapacity = "TokenBucketCapacity"
	//TokenBucketFillInterval time.Duration ...
	TokenBucketFillInterval = "TokenBucketFillInterval"
	//TokenBucketFillCount int ...
	TokenBucketFillCount = "TokenBucketFillCount"
	//LeakyBucketRateLimitSwitch bool ...
	LeakyBucketRateLimitSwitch = "LeakyBucketRateLimitSwitch"
	//LeakyBucketCapacity int ...
	LeakyBucketCapacity = "LeakyBucketCapacity"
	//LeakyBucketInterval ...
	LeakyBucketInterval = "LeakyBucketInterval"
)

//config default value
const (
	//DefaultEnableConnectionPool ...
	DefaultEnableConnectionPool bool = true
	//DefaultMaxConnectionsPerHost ...
	DefaultMaxConnectionsPerHost int = 50
	//DefaultMaxTotalConnections ...
	DefaultMaxTotalConnections int = 200
	//DefaultConnectTimeout ...
	DefaultConnectTimeout = 200 * time.Millisecond
	//DefaultReadTimeout ...
	DefaultReadWriteTimeout = 500 * time.Millisecond
	//DefaultRequestTimeout ...
	DefaultRequestTimeout = 500 * time.Millisecond
	//DefaultMaxAutoRetries
	DefaultMaxAutoRetries int = 0
	//DefaultMaxAutoRetriesNextServer ...
	DefaultMaxAutoRetriesNextServer int = 1
	//DefaultOKToRetryOnAllOperations ...
	DefaultOKToRetryOnAllOperations bool = false
	//DefaultPort ...
	DefaultPort int = 80
	//DefaultListOfServers ...
	DefaultListOfServers string = ""
	//DefaultConnectionFailureThreshold ...
	DefaultConnectionFailureThreshold = 5
	//DefaultCircuitTrippedTimeoutFactor ...
	DefaultCircuitTrippedTimeoutFactor = 10
	//DefaultCircuitTripMaxTimeout ...
	DefaultCircuitTripMaxTimeout = 30 * time.Second
	//DefaultPingInterval ...
	DefaultPingInterval = 5 * time.Second
	//DefaultPingStrategy ...
	DefaultPingStrategy = "SerialPingStrategy"
	//DefaultLoadBalancerRule ...
	DefaultLoadBalancerRule = "RandomRule"
	//DefaultLoadBalancerKey ...
	DefaultLoadBalancerKey = "marathon"
	//DefaultListOfServersPollingInterval ...
	DefaultListOfServersPollingInterval = 30 * time.Second
	//DefaultConcurrencyRateLimitSwitch ...
	DefaultConcurrencyRateLimitSwitch = false
	//DefaultTokenBucketRateLimitSwitch ...
	DefaultTokenBucketRateLimitSwitch = false
	//DefaultTokenBucketCapacity ...
	DefaultTokenBucketCapacity = 50
	//DefaultTokenBucketFillInterval ...
	DefaultTokenBucketFillInterval = 100 * time.Millisecond
	//DefaultTokenBucketFillCount ...
	DefaultTokenBucketFillCount = 2
	//DefaultLeakyBucketRateLimitSwitch ...
	DefaultLeakyBucketRateLimitSwitch = false
	//DefaultLeakyBucketCapacity ...
	DefaultLeakyBucketCapacity = 50
	//DefaultLeakyBucketInterval ...
	DefaultLeakyBucketInterval = 20 * time.Millisecond
	//DefaultRequestCountsSlidingWindowSize ...
	DefaultRequestCountsSlidingWindowSize = 300 // means save 300 seconds data
	//DefaultResponseTimeWindowSize ...
	DefaultResponseTimeWindowSize = 300 // means save 300 seconds data
)

//PingStrategy ...
const (
	//SerialPingStrategy ...
	SerialPingStrategy = "SerialPingStrategy"
	//ParallelPingStrategy ...
	ParallelPingStrategy = "ParallelPingStrategy"
)

//LoadBalancer Rule
const (
	//RandomLBRule ...
	RandomLBRule = "RandomRule"
	//RoundRobinLBRule ...
	RoundRobinLBRule = "RoundRobinRule"
)
